function Hd = EEG_FIR
%EEG_FIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 06-Dec-2021 19:25:43

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency

Fpass1 = 59.5;             % First Passband Frequency
Fstop1 = 59.9;             % First Stopband Frequency
Fstop2 = 60.1;             % Second Stopband Frequency
Fpass2 = 60.5;             % Second Passband Frequency
Dpass1 = 0.0057563991496;  % First Passband Ripple
Dstop  = 0.14125375446;    % Stopband Attenuation
Dpass2 = 0.0057563991496;  % Second Passband Ripple
dens   = 20;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass1 Fstop1 Fstop2 Fpass2]/(Fs/2), [1 0 ...
                          1], [Dpass1 Dstop Dpass2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
