function Hd = EEG_IIR
%EEG_IIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 06-Dec-2021 19:24:36

% Chebyshev Type II Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency

N      = 4;     % Order
Fstop1 = 59.9;  % First Stopband Frequency
Fstop2 = 60.1;  % Second Stopband Frequency
Astop  = 15;    % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandstop('N,Fst1,Fst2,Ast', N, Fstop1, Fstop2, Astop, Fs);
Hd = design(h, 'cheby2');

% [EOF]
