function Hd = VGRF_FIR2
%VGRF_FIR2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 06-Dec-2021 23:23:21

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 100;  % Sampling Frequency

Fstop1 = 0.1;             % First Stopband Frequency
Fpass1 = 0.4;             % First Passband Frequency
Fpass2 = 9.7;             % Second Passband Frequency
Fstop2 = 10;              % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.028774368332;  % Passband Ripple
Dstop2 = 0.01;            % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
